/*VER: 1*/ 
#ifndef PageID_OrgId_Relation_HEADER_INCLUDE_071015_YKS1
#define PageID_OrgId_Relation_HEADER_INCLUDE_071015_YKS1

//Code Generated by yangks for HaiNan. 2007.10.15

#include "TOCIQuery.h"
#include "Environment.h"
#include "CommonMacro.h"
#include "KeyTree.h"

/*
create table b_PageID_Orgid_relation (
    relation_id  number(9),
    ip           varchar2(15),
    Page_id      number(9),
    org_id       number(9)
);
alter table B_PAGEID_ORGID_RELATION
  add constraint PK_PAGEID_ORGID_RELA primary key (RELATION_ID)
  using index;
alter table B_PAGEID_ORGID_RELATION
  add constraint UK_PAGEID_IP unique (IP, PAGE_ID)
  using index ;

即将完成的功能：
    根据IP、PageID 确定小灵通所在地OrgID
    在标准事件模型上,借用字段 接入IP/接入端口两个属性
*/

class CheckIpPageItem
{
  public:
    long  m_lOrgID;
    int   m_iMinCheckLen;
};

class IpPageConvToOrg
{
  public:
    
    static bool m_bInited;
        
    //static KeyTree<long> *m_pIpPageTree;
    static KeyTree<CheckIpPageItem> *m_pIpPageTree;
    
    static void load ();
    
    static bool convert (EventSection *pEvt);
};

#endif
