#ifndef CTPCONF_H_
#define CTPCONF_H_

#define CTP_PROCESS_NAME "ctpc"

#ifdef CTP_PUT
	#define CTP_MODULE_NO "28"
#else
	#define CTP_MODULE_NO "27"
#endif	

#define CTP_CONFIG_FILE "etc/ctp_client"
#define COMMON_CONFIG_FILE "etc/common"
#define CTP_ENV_CONFIG "EXC_HOME"
#define CTP_ENV_DATA "EXC_DATA"
#define CTP_TEMP_FILE_FLAG "~"

#define CTP_LOG_TYPE_PUT "30"
#define CTP_LOG_TYPE_GET "31"
#define CTP_LOG_TYPE_SCAN "34"

#define CTP_LOG_DIRECTION_SEND "0"
#define CTP_LOG_DIRECTION_RECV "1"

#define CTP_LOG_WARNING "W"

#ifdef CTP_DEBUG
	#define CTP_DEBUG_OUTPUT "stdout"
#endif	

#define CTP_OK 0
#define CTP_ERROR -1
#define CTP_HALF -2

#define CTP_TRUE 1
#define CTP_FALSE 0

#define CTP_RENM_FAIL_CONFIREM_CNT 3

#define CTP_MAX_IP_SIZE 16
#define CTP_MAX_PORT_SIZE 16
#define CTP_MAX_USR_SIZE 64
#define CTP_MAX_PWD_SIZE 64
#define CTP_MAX_FILTER_SIZE 64
#define CTP_MAX_PATH_SIZE 1024
#define CTP_TIME_STR_SIZE 14

#define CTP_ALERT_CONNECT 16101
#define CTP_ALERT_AUTH 16102
#define CTP_ALERT_LIST 16103
#define CTP_ALERT_PUT 16104
#define CTP_ALERT_GET 16105
#define CTP_ALERT_QUIT 16106
#define CTP_ALERT_LINK 16107
#define CTP_ALERT_DELF 16108
#define CTP_ALERT_LOW_SPEED 16109
#define CTP_ALERT_MV 16110
#define CTP_ALERT_MISS_PARAM 16111
#define CTP_ALERT_SCHED_CONNECT 16112
#define CTP_ALERT_UNKOWN_SCHED 16113
#define CTP_ALERT_UNKOWN_TASK 16114
#define CTP_ALERT_GET_PARAM 16115
#define CTP_ALERT_UPDATE_FILE_STAT 16116
#define CTP_ALERT_COMMIT_RESULT 16117
#define CTP_ALERT_RENM 16118
#define CTP_ALERT_SIZE 16119
#define CTP_ALERT_CTPINIT 16120
#define CTP_ALERT_SDELF 16121
#define CTP_ALERT_LOG 16122
#define CTP_ALERT_AC 16123
#define CTP_ALERT_INDEX 16124
#define CTP_ALERT_ARBITRAGE 16125
#define CTP_ALERT_GET_MODE 16126
#define CTP_ALERT_FILE_SIZE 16127
#define CTP_ALERT_LRENM 16128
#define CTP_ALERT_DUPLICATE_FILE 13107

#endif
