/* soapClient.c
   Generated by gSOAP 2.7.15 from WebService.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.7.15 2010-11-09 08:06:56 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetVpdnIPByImsi(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetVpdnIPByImsi *ns1__GetVpdnIPByImsi, struct _ns1__GetVpdnIPByImsiResponse *ns1__GetVpdnIPByImsiResponse)
{	struct __ns1__GetVpdnIPByImsi soap_tmp___ns1__GetVpdnIPByImsi;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.131.134:9953/services/CVpdnIpService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetVpdnIPByImsi.ns1__GetVpdnIPByImsi = ns1__GetVpdnIPByImsi;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetVpdnIPByImsi(soap, &soap_tmp___ns1__GetVpdnIPByImsi);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetVpdnIPByImsi(soap, &soap_tmp___ns1__GetVpdnIPByImsi, "-ns1:GetVpdnIPByImsi", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetVpdnIPByImsi(soap, &soap_tmp___ns1__GetVpdnIPByImsi, "-ns1:GetVpdnIPByImsi", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetVpdnIPByImsiResponse)
		return soap_closesock(soap);
	soap_default__ns1__GetVpdnIPByImsiResponse(soap, ns1__GetVpdnIPByImsiResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetVpdnIPByImsiResponse(soap, ns1__GetVpdnIPByImsiResponse, "ns1:GetVpdnIPByImsiResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetVpdnOnlineIPByImsi(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetVpdnOnlineIPByImsi *ns1__GetVpdnOnlineIPByImsi, struct _ns1__GetVpdnOnlineIPByImsiResponse *ns1__GetVpdnOnlineIPByImsiResponse)
{	struct __ns1__GetVpdnOnlineIPByImsi soap_tmp___ns1__GetVpdnOnlineIPByImsi;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.131.134:9953/services/CVpdnIpService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetVpdnOnlineIPByImsi.ns1__GetVpdnOnlineIPByImsi = ns1__GetVpdnOnlineIPByImsi;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetVpdnOnlineIPByImsi(soap, &soap_tmp___ns1__GetVpdnOnlineIPByImsi);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetVpdnOnlineIPByImsi(soap, &soap_tmp___ns1__GetVpdnOnlineIPByImsi, "-ns1:GetVpdnOnlineIPByImsi", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetVpdnOnlineIPByImsi(soap, &soap_tmp___ns1__GetVpdnOnlineIPByImsi, "-ns1:GetVpdnOnlineIPByImsi", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetVpdnOnlineIPByImsiResponse)
		return soap_closesock(soap);
	soap_default__ns1__GetVpdnOnlineIPByImsiResponse(soap, ns1__GetVpdnOnlineIPByImsiResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__GetVpdnOnlineIPByImsiResponse(soap, ns1__GetVpdnOnlineIPByImsiResponse, "ns1:GetVpdnOnlineIPByImsiResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeSql(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeSql *ns2__executeSql, struct _ns2__executeSqlResponse *ns2__executeSqlResponse)
{	struct __ns2__executeSql soap_tmp___ns2__executeSql;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__executeSql.ns2__executeSql = ns2__executeSql;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__executeSql(soap, &soap_tmp___ns2__executeSql);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__executeSql(soap, &soap_tmp___ns2__executeSql, "-ns2:executeSql", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__executeSql(soap, &soap_tmp___ns2__executeSql, "-ns2:executeSql", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__executeSqlResponse)
		return soap_closesock(soap);
	soap_default__ns2__executeSqlResponse(soap, ns2__executeSqlResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__executeSqlResponse(soap, ns2__executeSqlResponse, "ns2:executeSqlResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeUpdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeUpdate *ns2__executeUpdate, struct _ns2__executeUpdateResponse *ns2__executeUpdateResponse)
{	struct __ns2__executeUpdate soap_tmp___ns2__executeUpdate;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__executeUpdate.ns2__executeUpdate = ns2__executeUpdate;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__executeUpdate(soap, &soap_tmp___ns2__executeUpdate);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__executeUpdate(soap, &soap_tmp___ns2__executeUpdate, "-ns2:executeUpdate", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__executeUpdate(soap, &soap_tmp___ns2__executeUpdate, "-ns2:executeUpdate", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__executeUpdateResponse)
		return soap_closesock(soap);
	soap_default__ns2__executeUpdateResponse(soap, ns2__executeUpdateResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__executeUpdateResponse(soap, ns2__executeUpdateResponse, "ns2:executeUpdateResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeSqlEx(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeSqlEx *ns2__executeSqlEx, struct _ns2__executeSqlExResponse *ns2__executeSqlExResponse)
{	struct __ns2__executeSqlEx soap_tmp___ns2__executeSqlEx;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__executeSqlEx.ns2__executeSqlEx = ns2__executeSqlEx;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__executeSqlEx(soap, &soap_tmp___ns2__executeSqlEx);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__executeSqlEx(soap, &soap_tmp___ns2__executeSqlEx, "-ns2:executeSqlEx", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__executeSqlEx(soap, &soap_tmp___ns2__executeSqlEx, "-ns2:executeSqlEx", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__executeSqlExResponse)
		return soap_closesock(soap);
	soap_default__ns2__executeSqlExResponse(soap, ns2__executeSqlExResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__executeSqlExResponse(soap, ns2__executeSqlExResponse, "ns2:executeSqlExResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeProcedureEx(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeProcedureEx *ns2__executeProcedureEx, struct _ns2__executeProcedureExResponse *ns2__executeProcedureExResponse)
{	struct __ns2__executeProcedureEx soap_tmp___ns2__executeProcedureEx;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__executeProcedureEx.ns2__executeProcedureEx = ns2__executeProcedureEx;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__executeProcedureEx(soap, &soap_tmp___ns2__executeProcedureEx);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__executeProcedureEx(soap, &soap_tmp___ns2__executeProcedureEx, "-ns2:executeProcedureEx", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__executeProcedureEx(soap, &soap_tmp___ns2__executeProcedureEx, "-ns2:executeProcedureEx", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__executeProcedureExResponse)
		return soap_closesock(soap);
	soap_default__ns2__executeProcedureExResponse(soap, ns2__executeProcedureExResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__executeProcedureExResponse(soap, ns2__executeProcedureExResponse, "ns2:executeProcedureExResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeQuery *ns2__executeQuery, struct _ns2__executeQueryResponse *ns2__executeQueryResponse)
{	struct __ns2__executeQuery soap_tmp___ns2__executeQuery;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__executeQuery.ns2__executeQuery = ns2__executeQuery;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__executeQuery(soap, &soap_tmp___ns2__executeQuery);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__executeQuery(soap, &soap_tmp___ns2__executeQuery, "-ns2:executeQuery", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__executeQuery(soap, &soap_tmp___ns2__executeQuery, "-ns2:executeQuery", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__executeQueryResponse)
		return soap_closesock(soap);
	soap_default__ns2__executeQueryResponse(soap, ns2__executeQueryResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__executeQueryResponse(soap, ns2__executeQueryResponse, "ns2:executeQueryResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeQueryEx(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeQueryEx *ns2__executeQueryEx, struct _ns2__executeQueryExResponse *ns2__executeQueryExResponse)
{	struct __ns2__executeQueryEx soap_tmp___ns2__executeQueryEx;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__executeQueryEx.ns2__executeQueryEx = ns2__executeQueryEx;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__executeQueryEx(soap, &soap_tmp___ns2__executeQueryEx);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__executeQueryEx(soap, &soap_tmp___ns2__executeQueryEx, "-ns2:executeQueryEx", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__executeQueryEx(soap, &soap_tmp___ns2__executeQueryEx, "-ns2:executeQueryEx", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__executeQueryExResponse)
		return soap_closesock(soap);
	soap_default__ns2__executeQueryExResponse(soap, ns2__executeQueryExResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__executeQueryExResponse(soap, ns2__executeQueryExResponse, "ns2:executeQueryExResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeProcedure(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeProcedure *ns2__executeProcedure, struct _ns2__executeProcedureResponse *ns2__executeProcedureResponse)
{	struct __ns2__executeProcedure soap_tmp___ns2__executeProcedure;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__executeProcedure.ns2__executeProcedure = ns2__executeProcedure;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__executeProcedure(soap, &soap_tmp___ns2__executeProcedure);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__executeProcedure(soap, &soap_tmp___ns2__executeProcedure, "-ns2:executeProcedure", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__executeProcedure(soap, &soap_tmp___ns2__executeProcedure, "-ns2:executeProcedure", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__executeProcedureResponse)
		return soap_closesock(soap);
	soap_default__ns2__executeProcedureResponse(soap, ns2__executeProcedureResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__executeProcedureResponse(soap, ns2__executeProcedureResponse, "ns2:executeProcedureResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeQueryOra(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeQueryOra *ns2__executeQueryOra, struct _ns2__executeQueryOraResponse *ns2__executeQueryOraResponse)
{	struct __ns2__executeQueryOra soap_tmp___ns2__executeQueryOra;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__executeQueryOra.ns2__executeQueryOra = ns2__executeQueryOra;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__executeQueryOra(soap, &soap_tmp___ns2__executeQueryOra);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__executeQueryOra(soap, &soap_tmp___ns2__executeQueryOra, "-ns2:executeQueryOra", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__executeQueryOra(soap, &soap_tmp___ns2__executeQueryOra, "-ns2:executeQueryOra", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__executeQueryOraResponse)
		return soap_closesock(soap);
	soap_default__ns2__executeQueryOraResponse(soap, ns2__executeQueryOraResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__executeQueryOraResponse(soap, ns2__executeQueryOraResponse, "ns2:executeQueryOraResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeXML(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeXML *ns2__executeXML, struct _ns2__executeXMLResponse *ns2__executeXMLResponse)
{	struct __ns2__executeXML soap_tmp___ns2__executeXML;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__executeXML.ns2__executeXML = ns2__executeXML;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__executeXML(soap, &soap_tmp___ns2__executeXML);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__executeXML(soap, &soap_tmp___ns2__executeXML, "-ns2:executeXML", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__executeXML(soap, &soap_tmp___ns2__executeXML, "-ns2:executeXML", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__executeXMLResponse)
		return soap_closesock(soap);
	soap_default__ns2__executeXMLResponse(soap, ns2__executeXMLResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__executeXMLResponse(soap, ns2__executeXMLResponse, "ns2:executeXMLResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__call(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__call *ns2__call, struct _ns2__callResponse *ns2__callResponse)
{	struct __ns2__call soap_tmp___ns2__call;
	if (!soap_endpoint)
		soap_endpoint = "http://132.228.91.6:80/ccatsida/services/AsigService";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__call.ns2__call = ns2__call;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__call(soap, &soap_tmp___ns2__call);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__call(soap, &soap_tmp___ns2__call, "-ns2:call", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__call(soap, &soap_tmp___ns2__call, "-ns2:call", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns2__callResponse)
		return soap_closesock(soap);
	soap_default__ns2__callResponse(soap, ns2__callResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns2__callResponse(soap, ns2__callResponse, "ns2:callResponse", "");
	if (soap->error)
	{	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
			return soap_recv_fault(soap);
		return soap_closesock(soap);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
