/* soapStub.h
   Generated by gSOAP 2.7.15 from WebService.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://vpdn.webservice.lcbms.linkage.com"
#define SOAP_NAMESPACE_OF_ns2	"http://main.asig.regaltec.com"
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_ns1__VpdnIPRequest
#define SOAP_TYPE_ns1__VpdnIPRequest (7)
/* ns1:VpdnIPRequest */
struct ns1__VpdnIPRequest
{
	char *imsi;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__VpdnIPResponse
#define SOAP_TYPE_ns1__VpdnIPResponse (8)
/* ns1:VpdnIPResponse */
struct ns1__VpdnIPResponse
{
	char *ip;	/* optional element of type xsd:string */
	int ret;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__VpdnOnlineIPRequest
#define SOAP_TYPE_ns1__VpdnOnlineIPRequest (9)
/* ns1:VpdnOnlineIPRequest */
struct ns1__VpdnOnlineIPRequest
{
	char *imsi;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__VpdnOnlineIPResponse
#define SOAP_TYPE_ns1__VpdnOnlineIPResponse (10)
/* ns1:VpdnOnlineIPResponse */
struct ns1__VpdnOnlineIPResponse
{
	char *ip;	/* optional element of type xsd:string */
	int ret;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns1__GetVpdnIPByImsi
#define SOAP_TYPE__ns1__GetVpdnIPByImsi (11)
/* ns1:GetVpdnIPByImsi */
struct _ns1__GetVpdnIPByImsi
{
	struct ns1__VpdnIPRequest *request;	/* required element of type ns1:VpdnIPRequest */
};
#endif

#ifndef SOAP_TYPE__ns1__GetVpdnIPByImsiResponse
#define SOAP_TYPE__ns1__GetVpdnIPByImsiResponse (13)
/* ns1:GetVpdnIPByImsiResponse */
struct _ns1__GetVpdnIPByImsiResponse
{
	struct ns1__VpdnIPResponse *GetVpdnIPByImsiReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:VpdnIPResponse */
};
#endif

#ifndef SOAP_TYPE__ns1__GetVpdnOnlineIPByImsi
#define SOAP_TYPE__ns1__GetVpdnOnlineIPByImsi (15)
/* ns1:GetVpdnOnlineIPByImsi */
struct _ns1__GetVpdnOnlineIPByImsi
{
	struct ns1__VpdnOnlineIPRequest *request;	/* required element of type ns1:VpdnOnlineIPRequest */
};
#endif

#ifndef SOAP_TYPE__ns1__GetVpdnOnlineIPByImsiResponse
#define SOAP_TYPE__ns1__GetVpdnOnlineIPByImsiResponse (17)
/* ns1:GetVpdnOnlineIPByImsiResponse */
struct _ns1__GetVpdnOnlineIPByImsiResponse
{
	struct ns1__VpdnOnlineIPResponse *GetVpdnOnlineIPByImsiReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ns1:VpdnOnlineIPResponse */
};
#endif

#ifndef SOAP_TYPE__ns2__executeSql
#define SOAP_TYPE__ns2__executeSql (19)
/* ns2:executeSql */
struct _ns2__executeSql
{
	char *sqlId;	/* optional element of type xsd:string */
	char *sqlParam;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeSqlResponse
#define SOAP_TYPE__ns2__executeSqlResponse (20)
/* ns2:executeSqlResponse */
struct _ns2__executeSqlResponse
{
	char *executeSqlReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeUpdate
#define SOAP_TYPE__ns2__executeUpdate (21)
/* ns2:executeUpdate */
struct _ns2__executeUpdate
{
	char *sql;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeUpdateResponse
#define SOAP_TYPE__ns2__executeUpdateResponse (22)
/* ns2:executeUpdateResponse */
struct _ns2__executeUpdateResponse
{
	char *executeUpdateReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeSqlEx
#define SOAP_TYPE__ns2__executeSqlEx (23)
/* ns2:executeSqlEx */
struct _ns2__executeSqlEx
{
	char *sqlId;	/* optional element of type xsd:string */
	char *sqlParam;	/* optional element of type xsd:string */
	int pageSize;	/* required element of type xsd:int */
	int Nowpage;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns2__executeSqlExResponse
#define SOAP_TYPE__ns2__executeSqlExResponse (24)
/* ns2:executeSqlExResponse */
struct _ns2__executeSqlExResponse
{
	char *executeSqlExReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeProcedureEx
#define SOAP_TYPE__ns2__executeProcedureEx (25)
/* ns2:executeProcedureEx */
struct _ns2__executeProcedureEx
{
	char *sql;	/* optional element of type xsd:string */
	char *sqlParam;	/* optional element of type xsd:string */
	int pageSize;	/* required element of type xsd:int */
	int nowPage;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns2__executeProcedureExResponse
#define SOAP_TYPE__ns2__executeProcedureExResponse (26)
/* ns2:executeProcedureExResponse */
struct _ns2__executeProcedureExResponse
{
	char *executeProcedureExReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeQuery
#define SOAP_TYPE__ns2__executeQuery (27)
/* ns2:executeQuery */
struct _ns2__executeQuery
{
	char *sql;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeQueryResponse
#define SOAP_TYPE__ns2__executeQueryResponse (28)
/* ns2:executeQueryResponse */
struct _ns2__executeQueryResponse
{
	char *executeQueryReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeQueryEx
#define SOAP_TYPE__ns2__executeQueryEx (29)
/* ns2:executeQueryEx */
struct _ns2__executeQueryEx
{
	char *sql;	/* optional element of type xsd:string */
	int pageSize;	/* required element of type xsd:int */
	int nowPage;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns2__executeQueryExResponse
#define SOAP_TYPE__ns2__executeQueryExResponse (30)
/* ns2:executeQueryExResponse */
struct _ns2__executeQueryExResponse
{
	char *executeQueryExReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeProcedure
#define SOAP_TYPE__ns2__executeProcedure (31)
/* ns2:executeProcedure */
struct _ns2__executeProcedure
{
	char *sql;	/* optional element of type xsd:string */
	char *sqlParam;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeProcedureResponse
#define SOAP_TYPE__ns2__executeProcedureResponse (32)
/* ns2:executeProcedureResponse */
struct _ns2__executeProcedureResponse
{
	char *executeProcedureReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeQueryOra
#define SOAP_TYPE__ns2__executeQueryOra (33)
/* ns2:executeQueryOra */
struct _ns2__executeQueryOra
{
	char *sql;	/* optional element of type xsd:string */
	int pageSize;	/* required element of type xsd:int */
	int nowPage;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE__ns2__executeQueryOraResponse
#define SOAP_TYPE__ns2__executeQueryOraResponse (34)
/* ns2:executeQueryOraResponse */
struct _ns2__executeQueryOraResponse
{
	char *executeQueryOraReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeXML
#define SOAP_TYPE__ns2__executeXML (35)
/* ns2:executeXML */
struct _ns2__executeXML
{
	char *inXmlString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__executeXMLResponse
#define SOAP_TYPE__ns2__executeXMLResponse (36)
/* ns2:executeXMLResponse */
struct _ns2__executeXMLResponse
{
	char *executeXMLReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__call
#define SOAP_TYPE__ns2__call (37)
/* ns2:call */
struct _ns2__call
{
	char *inXmlString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns2__callResponse
#define SOAP_TYPE__ns2__callResponse (38)
/* ns2:callResponse */
struct _ns2__callResponse
{
	char *callReturn;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE___ns1__GetVpdnIPByImsi
#define SOAP_TYPE___ns1__GetVpdnIPByImsi (42)
/* Operation wrapper: */
struct __ns1__GetVpdnIPByImsi
{
	struct _ns1__GetVpdnIPByImsi *ns1__GetVpdnIPByImsi;	/* optional element of type ns1:GetVpdnIPByImsi */
};
#endif

#ifndef SOAP_TYPE___ns1__GetVpdnOnlineIPByImsi
#define SOAP_TYPE___ns1__GetVpdnOnlineIPByImsi (46)
/* Operation wrapper: */
struct __ns1__GetVpdnOnlineIPByImsi
{
	struct _ns1__GetVpdnOnlineIPByImsi *ns1__GetVpdnOnlineIPByImsi;	/* optional element of type ns1:GetVpdnOnlineIPByImsi */
};
#endif

#ifndef SOAP_TYPE___ns2__executeSql
#define SOAP_TYPE___ns2__executeSql (50)
/* Operation wrapper: */
struct __ns2__executeSql
{
	struct _ns2__executeSql *ns2__executeSql;	/* optional element of type ns2:executeSql */
};
#endif

#ifndef SOAP_TYPE___ns2__executeUpdate
#define SOAP_TYPE___ns2__executeUpdate (54)
/* Operation wrapper: */
struct __ns2__executeUpdate
{
	struct _ns2__executeUpdate *ns2__executeUpdate;	/* optional element of type ns2:executeUpdate */
};
#endif

#ifndef SOAP_TYPE___ns2__executeSqlEx
#define SOAP_TYPE___ns2__executeSqlEx (58)
/* Operation wrapper: */
struct __ns2__executeSqlEx
{
	struct _ns2__executeSqlEx *ns2__executeSqlEx;	/* optional element of type ns2:executeSqlEx */
};
#endif

#ifndef SOAP_TYPE___ns2__executeProcedureEx
#define SOAP_TYPE___ns2__executeProcedureEx (62)
/* Operation wrapper: */
struct __ns2__executeProcedureEx
{
	struct _ns2__executeProcedureEx *ns2__executeProcedureEx;	/* optional element of type ns2:executeProcedureEx */
};
#endif

#ifndef SOAP_TYPE___ns2__executeQuery
#define SOAP_TYPE___ns2__executeQuery (66)
/* Operation wrapper: */
struct __ns2__executeQuery
{
	struct _ns2__executeQuery *ns2__executeQuery;	/* optional element of type ns2:executeQuery */
};
#endif

#ifndef SOAP_TYPE___ns2__executeQueryEx
#define SOAP_TYPE___ns2__executeQueryEx (70)
/* Operation wrapper: */
struct __ns2__executeQueryEx
{
	struct _ns2__executeQueryEx *ns2__executeQueryEx;	/* optional element of type ns2:executeQueryEx */
};
#endif

#ifndef SOAP_TYPE___ns2__executeProcedure
#define SOAP_TYPE___ns2__executeProcedure (74)
/* Operation wrapper: */
struct __ns2__executeProcedure
{
	struct _ns2__executeProcedure *ns2__executeProcedure;	/* optional element of type ns2:executeProcedure */
};
#endif

#ifndef SOAP_TYPE___ns2__executeQueryOra
#define SOAP_TYPE___ns2__executeQueryOra (78)
/* Operation wrapper: */
struct __ns2__executeQueryOra
{
	struct _ns2__executeQueryOra *ns2__executeQueryOra;	/* optional element of type ns2:executeQueryOra */
};
#endif

#ifndef SOAP_TYPE___ns2__executeXML
#define SOAP_TYPE___ns2__executeXML (82)
/* Operation wrapper: */
struct __ns2__executeXML
{
	struct _ns2__executeXML *ns2__executeXML;	/* optional element of type ns2:executeXML */
};
#endif

#ifndef SOAP_TYPE___ns2__call
#define SOAP_TYPE___ns2__call (86)
/* Operation wrapper: */
struct __ns2__call
{
	struct _ns2__call *ns2__call;	/* optional element of type ns2:call */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (87)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (88)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (90)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (93)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (94)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetVpdnIPByImsi(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetVpdnIPByImsi *ns1__GetVpdnIPByImsi, struct _ns1__GetVpdnIPByImsiResponse *ns1__GetVpdnIPByImsiResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetVpdnOnlineIPByImsi(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetVpdnOnlineIPByImsi *ns1__GetVpdnOnlineIPByImsi, struct _ns1__GetVpdnOnlineIPByImsiResponse *ns1__GetVpdnOnlineIPByImsiResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeSql(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeSql *ns2__executeSql, struct _ns2__executeSqlResponse *ns2__executeSqlResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeUpdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeUpdate *ns2__executeUpdate, struct _ns2__executeUpdateResponse *ns2__executeUpdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeSqlEx(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeSqlEx *ns2__executeSqlEx, struct _ns2__executeSqlExResponse *ns2__executeSqlExResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeProcedureEx(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeProcedureEx *ns2__executeProcedureEx, struct _ns2__executeProcedureExResponse *ns2__executeProcedureExResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeQuery(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeQuery *ns2__executeQuery, struct _ns2__executeQueryResponse *ns2__executeQueryResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeQueryEx(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeQueryEx *ns2__executeQueryEx, struct _ns2__executeQueryExResponse *ns2__executeQueryExResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeProcedure(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeProcedure *ns2__executeProcedure, struct _ns2__executeProcedureResponse *ns2__executeProcedureResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeQueryOra(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeQueryOra *ns2__executeQueryOra, struct _ns2__executeQueryOraResponse *ns2__executeQueryOraResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__executeXML(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__executeXML *ns2__executeXML, struct _ns2__executeXMLResponse *ns2__executeXMLResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__call(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns2__call *ns2__call, struct _ns2__callResponse *ns2__callResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
