#ifndef _SHM_PARAM_DEF_HEAD_
#define _SHM_PARAM_DEF_HEAD_
#include "SHMData.h"
#include "SHMIntHashIndex.h"
#include "SHMStringTreeIndex.h"
#include "SHMParamCfg.h"

#define BUFF_MIN_SIZE 256
#define BUFF_MAX_SIZE 1024
#define _SHM_STRING_KEY_LEN_                   8
#define _SHM_FILE_NUMBER_                      100

//共享内存全局变量包含告警阈值、可扩展次数、每次扩展的空间
#define _SHM_PARAM_DATA_INITSIZE_               SHMParamCfg::getValue("memory","object.init_data_size")
#define _SHM_PARAM_EXTENTS_SIZE_              SHMParamCfg::getValue("memory","object.memory_ext_data_size")
#define _SHM_PARAM_EXTENTS_MAX_NUM_           SHMParamCfg::getValue("memory","object.memory_max_extents")
#define _SHM_PARAM_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","object.memory_ext_hwm")
#define _SHM_PARAM_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","object.shm_hwm_warming")
#define _SHM_PARAM_DATA_MAXSIZE_           SHMParamCfg::getValue("memory","object.max_shm_size")

//局部变量（精确到各张文件的配置(包含告警阈值、可扩展次数、每次扩展的空间)
#define _SHM_CONTEXTDATA_DATA_KEY_           SHMParamCfg::getValue("memory","context_filter_data.ipc_key_value")
#define _SHM_CONTEXTDATA_INDEX_KEY_          SHMParamCfg::getValue("memory","context_filter_index.ipc_key_value")
#define _SHM_CONTEXTDATA_SPACE_INITSIZE_         SHMParamCfg::getValue("memory","context_filter_data.init_data_size")
#define _SHM_CONTEXTDATA_SPACE_MAXSIZE_         SHMParamCfg::getValue("memory","context_filter_data.max_data_size")
#define _SHM_CONTEXTDATA_EXTENTS_NUM_         SHMParamCfg::getValue("memory","context_filter_data.memory_extents_num")
#define _SHM_CONTEXTDATA_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","context_filter_data.memory_max_extents")
#define _SHM_CONTEXTDATA_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","context_filter_data.memory_ext_data_size")
#define _SHM_CONTEXTDATA_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","context_filter_data.memory_ext_hwm")
#define _SHM_CONTEXTDATA_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","context_filter_data.shm_hwm_warming")
#define _SHM_CONTEXTDATA_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","context_filter_index.ipc_key_name",x)
#define _SHM_CONTEXTDATA_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","context_filter_data.ipc_key_name",x)
#define _SHM_CONTEXTDATA_KEY_MAXSIZE_        8
#define _PV_CONTEXTDATA_KEY_                SHMParamCfg::getValue("memory","context_filter_pv.ipc_key_value")

#define _SHM_MSGMAPINFO_DATA_KEY_            SHMParamCfg::getValue("memory","tabmsgmap_data.ipc_key_value")
#define _SHM_MSGMAPINFO_EXTENTS_NUM_         SHMParamCfg::getValue("memory","tabmsgmap_data.memory_extents_num")
#define _SHM_MSGMAPINFO_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","tabmsgmap_data.memory_max_extents")
#define _SHM_MSGMAPINFO_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","tabmsgmap_data.memory_ext_data_size")
#define _SHM_MSGMAPINFO_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","tabmsgmap_data.memory_ext_hwm")
#define _SHM_MSGMAPINFO_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","tabmsgmap_data.shm_hwm_warming")
#define _SHM_MSGMAPINFO_INDEX_KEY_           SHMParamCfg::getValue("memory","tabmsgmap_index.ipc_key_value")
#define _SHM_MSGMAPINFO_SPACE_INITSIZE_          SHMParamCfg::getValue("memory","tabmsgmap_data.init_data_size")
#define _SHM_MSGMAPINFO_SPACE_MAXSIZE_          SHMParamCfg::getValue("memory","tabmsgmap_data.max_data_size")
#define _SHM_MSGMAPINFO_DATA_KEYNAME_(x)          SHMParamCfg::getString("memory","tabmsgmap_data.ipc_key_name",x)
#define _SHM_MSGMAPINFO_INDEX_KEYNAME_(x)          SHMParamCfg::getString("memory","tabmsgmap_index.ipc_key_name",x)
#define _PV_MSGMAPINFO_KEY_                  SHMParamCfg::getValue("memory","tabmsgmap_pv.ipc_key_value")

#define _SHM_SERVICETXTLIST_DATA_KEY_         SHMParamCfg::getValue("memory","servicetxtlist_data.ipc_key_value")
#define _SHM_SERVICETXTLIST_INDEX_KEY_        SHMParamCfg::getValue("memory","servicetxtlist_index.ipc_key_value")
#define _SHM_SERVICETXTLIST_INDEX_KEY_A_        SHMParamCfg::getValue("memory","servicetxtlist_a_index.ipc_key_value")
#define _SHM_SERVICETXTLIST_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","servicetxtlist_data.init_data_size")
#define _SHM_SERVICETXTLIST_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","servicetxtlist_data.max_data_size")
#define _SHM_SERVICETXTLIST_EXTENTS_NUM_       SHMParamCfg::getValue("memory","servicetxtlist_data.memory_extents_num")
#define _SHM_SERVICETXTLIST_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","servicetxtlist_data.memory_max_extents")
#define _SHM_SERVICETXTLIST_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","servicetxtlist_data.memory_ext_data_size")
#define _SHM_SERVICETXTLIST_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","servicetxtlist_data.memory_ext_hwm")
#define _SHM_SERVICETXTLIST_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","servicetxtlist_data.shm_hwm_warming")
#define _SHM_SERVICETXTLIST_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","servicetxtlist_data.ipc_key_name",x)
#define _SHM_SERVICETXTLIST_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","servicetxtlist_index.ipc_key_name",x)
#define _SHM_SERVICETXTLIST_KEY_MAXSIZE_       8
#define _PV_SERVICETXTLIST_KEY_             SHMParamCfg::getValue("memory","servicetxtlist_pv.ipc_key_value")

#define _SHM_STREAMCTRLINFO_DATA_KEY_         SHMParamCfg::getValue("memory","streamctrlinfo_data.ipc_key_value")
#define _SHM_STREAMCTRLINFO_INDEX_KEY_        SHMParamCfg::getValue("memory","streamctrlinfo_index.ipc_key_value")
#define _SHM_STREAMCTRLINFO_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","streamctrlinfo_data.init_data_size")
#define _SHM_STREAMCTRLINFO_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","streamctrlinfo_data.max_data_size")
#define _SHM_STREAMCTRLINFO_EXTENTS_NUM_       SHMParamCfg::getValue("memory","streamctrlinfo_data.memory_extents_num")
#define _SHM_STREAMCTRLINFO_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","streamctrlinfo_data.memory_max_extents")
#define _SHM_STREAMCTRLINFO_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","streamctrlinfo_data.memory_ext_data_size")
#define _SHM_STREAMCTRLINFO_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","streamctrlinfo_data.memory_ext_hwm")
#define _SHM_STREAMCTRLINFO_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","streamctrlinfo_data.shm_hwm_warming")
#define _SHM_STREAMCTRLINFO_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","streamctrlinfo_data.ipc_key_name",x)
#define _SHM_STREAMCTRLINFO_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","streamctrlinfo_index.ipc_key_name",x)
#define _SHM_STREAMCTRLINFO_KEY_MAXSIZE_        8
#define _PV_STREAMCTRLINFO_KEY_               SHMParamCfg::getValue("memory","streamctrlinfo_pv.ipc_key_value")

#define _SHM_STREAMCTRLDATA_DATA_KEY_         SHMParamCfg::getValue("memory","streamctrldata.ipc_key_value")
#define _SHM_STREAMCTRLDATA_INDEX_KEY_        SHMParamCfg::getValue("memory","streamctrlindex.ipc_key_value")
#define _SHM_STREAMCTRLDATA_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","streamctrldata.init_data_size")
#define _SHM_STREAMCTRLDATA_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","streamctrldata.max_data_size")
#define _SHM_STREAMCTRLDATA_EXTENTS_NUM_       SHMParamCfg::getValue("memory","streamctrldata.memory_extents_num")
#define _SHM_STREAMCTRLDATA_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","streamctrldata.memory_max_extents")
#define _SHM_STREAMCTRLDATA_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","streamctrldata.memory_ext_data_size")
#define _SHM_STREAMCTRLDATA_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","streamctrldata.memory_ext_hwm")
#define _SHM_STREAMCTRLDATA_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","streamctrldata.shm_hwm_warming")
#define _SHM_STREAMCTRLDATA_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","streamctrldata.ipc_key_name",x)
#define _SHM_STREAMCTRLDATA_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","streamctrlindex.ipc_key_name",x)
#define _SHM_STREAMCTRLDATA_KEY_MAXSIZE_        8
#define _PV_STREAMCTRLDATA_KEY_               SHMParamCfg::getValue("memory","streamctrlpv.ipc_key_value")

#define _SHM_USERINFODATA_DATA_KEY_         SHMParamCfg::getValue("memory","userinfodata.ipc_key_value")
#define _SHM_USERINFODATA_INDEX_KEY_        SHMParamCfg::getValue("memory","userinfoindex.ipc_key_value")
#define _SHM_USERINFODATA_INDEX_KEY_A_        SHMParamCfg::getValue("memory","userinfoindex_a.ipc_key_value")
#define _SHM_USERINFODATA_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","userinfodata.init_data_size")
#define _SHM_USERINFODATA_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","userinfodata.max_data_size")
#define _SHM_USERINFODATA_EXTENTS_NUM_       SHMParamCfg::getValue("memory","userinfodata.memory_extents_num")
#define _SHM_USERINFODATA_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","userinfodata.memory_max_extents")
#define _SHM_USERINFODATA_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","userinfodata.memory_ext_data_size")
#define _SHM_USERINFODATA_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","userinfodata.memory_ext_hwm")
#define _SHM_USERINFODATA_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","userinfodata.shm_hwm_warming")
#define _SHM_USERINFODATA_KEY_MAXSIZE_        8
#define _PV_USERINFODATA_KEY_               SHMParamCfg::getValue("memory","userinfopv.ipc_key_value")
#define _SHM_USERINFODATA_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","userinfodata.ipc_key_name",x)
#define _SHM_USERINFODATA_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","userinfoindex.ipc_key_name",x)
#define _SHM_USERINFODATA_INDEX_KEYNAME_A_(x)           SHMParamCfg::getString("memory","userinfoindex_a.ipc_key_name",x)

#define _SHM_SGWSLAQUEUE_DATA_KEY_         SHMParamCfg::getValue("memory","sgeslaquereldata.ipc_key_value")
#define _SHM_SGWSLAQUEUE_INDEX_KEY_        SHMParamCfg::getValue("memory","sgeslaquerelindex.ipc_key_value")
#define _SHM_SGWSLAQUEUE_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","sgeslaquereldata.init_data_size")
#define _SHM_SGWSLAQUEUE_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","sgeslaquereldata.max_data_size")
#define _SHM_SGWSLAQUEUE_EXTENTS_NUM_       SHMParamCfg::getValue("memory","sgeslaquereldata.memory_extents_num")
#define _SHM_SGWSLAQUEUE_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","sgeslaquereldata.memory_max_extents")
#define _SHM_SGWSLAQUEUE_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","sgeslaquereldata.memory_ext_data_size")
#define _SHM_SGWSLAQUEUE_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","sgeslaquereldata.memory_ext_hwm")
#define _SHM_SGWSLAQUEUE_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","sgeslaquereldata.shm_hwm_warming")
#define _SHM_SGWSLAQUEUE_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","sgeslaquerelindex.ipc_key_name",x)
#define _SHM_SGWSLAQUEUE_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","sgeslaquereldata.ipc_key_name",x)
#define _SHM_SGWSLAQUEUE_KEY_MAXSIZE_        8
#define _PV_SGWSLAQUEUE_KEY_               SHMParamCfg::getValue("memory","sgeslaquerelpv.ipc_key_value")

#define _SHM_NETINFO_DATA_KEY_         SHMParamCfg::getValue("memory","netInfodata_data.ipc_key_value")
#define _SHM_NETINFO_INDEX_KEY_        SHMParamCfg::getValue("memory","netInfodata_index.ipc_key_value")
#define _SHM_NETINFO_INDEX_KEY_S_        SHMParamCfg::getValue("memory","netInfodata_s_index.ipc_key_value")
#define _SHM_NETINFO_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","netInfodata_data.init_data_size")
#define _SHM_NETINFO_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","netInfodata_data.max_data_size")
#define _SHM_NETINFO_EXTENTS_NUM_       SHMParamCfg::getValue("memory","netInfodata_data.memory_extents_num")
#define _SHM_NETINFO_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","netInfodata_data.memory_max_extents")
#define _SHM_NETINFO_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","netInfodata_data.memory_ext_data_size")
#define _SHM_NETINFO_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","netInfodata_data.memory_ext_hwm")
#define _SHM_NETINFO_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","netInfodata_data.shm_hwm_warming")
#define _SHM_NETINFO_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","netInfodata_data.ipc_key_name",x)
#define _SHM_NETINFO_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","netInfodata_index.ipc_key_name",x)
#define _SHM_NETINFO_INDEX_KEYNAME_A_(x)           SHMParamCfg::getString("memory","netInfodata_s_index.ipc_key_name",x)
#define _SHM_NETINFO_KEY_MAXSIZE_        8
#define _PV_NETINFO_KEY_               SHMParamCfg::getValue("memory","netInfodata_pv.ipc_key_value")

#define _SHM_SESSION_DATA_KEY_         SHMParamCfg::getValue("memory","session_data.ipc_key_value")
#define _SHM_SESSION_INDEX_KEY_        SHMParamCfg::getValue("memory","session_index.ipc_key_value")
#define _SHM_SESSION_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","session_data.init_data_size")
#define _SHM_SESSION_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","session_data.max_data_size")
#define _SHM_SESSION_EXTENTS_NUM_       SHMParamCfg::getValue("memory","session_data.memory_extents_num")
#define _SHM_SESSION_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","session_data.memory_max_extents")
#define _SHM_SESSION_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","session_data.memory_ext_data_size")
#define _SHM_SESSION_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","session_data.memory_ext_hwm")
#define _SHM_SESSION_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","session_data.shm_hwm_warming")
#define _SHM_SESSION_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","session_data.ipc_key_name",x)
#define _SHM_SESSION_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","session_index.ipc_key_name",x)
#define _SHM_SESSION_KEY_MAXSIZE_        8
#define _PV_SESSION_KEY_               SHMParamCfg::getValue("memory","session_pv.ipc_key_value")

#define _SHM_SESSIONCLEAR_DATA_KEY_         SHMParamCfg::getValue("memory","sessionclear_data.ipc_key_value",982349)
#define _SHM_SESSIONCLEAR_INDEX_KEY_        SHMParamCfg::getValue("memory","sessionclear_index.ipc_key_value",9823345)
#define _SHM_SESSIONCLEAR_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","sessionclear_data.init_data_size",3000)
// #define _SHM_SESSIONCLEAR_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","session_data.max_data_size")
// #define _SHM_SESSIONCLEAR_EXTENTS_NUM_       SHMParamCfg::getValue("memory","session_data.memory_extents_num")
// #define _SHM_SESSIONCLEAR_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","session_data.memory_max_extents")
// #define _SHM_SESSIONCLEAR_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","session_data.memory_ext_data_size")
// #define _SHM_SESSIONCLEAR_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","session_data.memory_ext_hwm")
// #define _SHM_SESSIONCLEAR_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","session_data.shm_hwm_warming")
// #define _SHM_SESSIONCLEAR_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","session_data.ipc_key_name",x)
// #define _SHM_SESSIONCLEAR_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","session_index.ipc_key_name",x)
#define _SHM_SESSIONCLEAR_KEY_MAXSIZE_        8
#define _PV_SESSIONCLEAR_KEY_               SHMParamCfg::getValue("memory","sessionclear_pv.ipc_key_value")

#define _SHM_CONGESTLEVEL_DATA_KEY_         SHMParamCfg::getValue("memory","shmcongestlevel_data.ipc_key_value")
#define _SHM_CONGESTLEVEL_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","shmcongestlevel_data.init_data_size")
#define _SHM_CONGESTLEVEL_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","shmcongestlevel_data.max_data_size")
#define _SHM_CONGESTLEVEL_EXTENTS_NUM_       SHMParamCfg::getValue("memory","shmcongestlevel_data.memory_extents_num")
#define _SHM_CONGESTLEVEL_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","shmcongestlevel_data.memory_max_extents")
#define _SHM_CONGESTLEVEL_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","shmcongestlevel_data.memory_ext_data_size")
#define _SHM_CONGESTLEVEL_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","shmcongestlevel_data.memory_ext_hwm")
#define _SHM_CONGESTLEVEL_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","shmcongestlevel_data.shm_hwm_warming")
#define _SHM_CONGESTLEVEL_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","shmcongestlevel_data.ipc_key_name",x)
#define _SHM_CONGESTLEVEL_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","shmcongestlevel_index.ipc_key_name",x)
#define _PV_CONGESTLEVEL_KEY_               SHMParamCfg::getValue("memory","shmcongestlevel_pv.ipc_key_value")

#define _SHM_SERVICETXTLISTBASE_DATA_KEY_         SHMParamCfg::getValue("memory","service_txt_list_base_data.ipc_key_value")
#define _SHM_SERVICETXTLISTBASE_INDEX_KEY_        SHMParamCfg::getValue("memory","service_txt_list_base_index.ipc_key_value")
#define _SHM_SERVICETXTLISTBASE_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","service_txt_list_base_data.init_data_size")
#define _SHM_SERVICETXTLISTBASE_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","service_txt_list_base_data.max_data_size")
#define _SHM_SERVICETXTLISTBASE_EXTENTS_NUM_       SHMParamCfg::getValue("memory","service_txt_list_base_data.memory_extents_num")
#define _SHM_SERVICETXTLISTBASE_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","service_txt_list_base_data.memory_max_extents")
#define _SHM_SERVICETXTLISTBASE_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","service_txt_list_base_data.memory_ext_data_size")
#define _SHM_SERVICETXTLISTBASE_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","service_txt_list_base_data.memory_ext_hwm")
#define _SHM_SERVICETXTLISTBASE_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","service_txt_list_base_data.shm_hwm_warming")
#define _SHM_SERVICETXTLISTBASE_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","service_txt_list_base_data.ipc_key_name",x)
#define _SHM_SERVICETXTLISTBASE_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","service_txt_list_base_index.ipc_key_name",x)
#define _SHM_SERVICETXTLISTBASE_KEY_MAXSIZE_        8
#define _PV_SERVICETXTLISTBASE_KEY_               SHMParamCfg::getValue("memory","service_txt_list_base_pv.ipc_key_value")

#define _SHM_LOADBALANCE_DATA_KEY_         SHMParamCfg::getValue("memory","loadbalancedata.ipc_key_value")
#define _SHM_LOADBALANCE_INDEX_KEY_        SHMParamCfg::getValue("memory","loadbalanceindex.ipc_key_value")
#define _SHM_LOADBALANCE_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","loadbalancedata.init_data_size")
#define _SHM_LOADBALANCE_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","loadbalancedata.max_data_size")
#define _SHM_LOADBALANCE_EXTENTS_NUM_       SHMParamCfg::getValue("memory","loadbalancedata.memory_extents_num")
#define _SHM_LOADBALANCE_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","loadbalancedata.memory_max_extents")
#define _SHM_LOADBALANCE_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","loadbalancedata.memory_ext_data_size")
#define _SHM_LOADBALANCE_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","loadbalancedata.memory_ext_hwm")
#define _SHM_LOADBALANCE_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","loadbalancedata.shm_hwm_warming")
#define _SHM_LOADBALANCE_DATE_KEYNAME_(x)           SHMParamCfg::getString("memory","loadbalancedata.ipc_key_name",x)
#define _SHM_LOADBALANCE_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","loadbalanceindex.ipc_key_name",x)
#define _SHM_LOADBALANCE_KEY_MAXSIZE_        8
#define _PV_LOADBALANCE_KEY_               SHMParamCfg::getValue("memory","loadbalancepv.ipc_key_value")

#define _SHM_BASEMETHOD_DATA_KEY_         SHMParamCfg::getValue("memory","basemethod_data.ipc_key_value")
#define _SHM_BASEMETHOD_INDEX_KEY_        SHMParamCfg::getValue("memory","basemethod_index.ipc_key_value")
#define _SHM_BASEMETHOD_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","basemethod_data.init_data_size")
#define _SHM_BASEMETHOD_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","basemethod_data.max_data_size")
#define _SHM_BASEMETHOD_EXTENTS_NUM_       SHMParamCfg::getValue("memory","basemethod_data.memory_extents_num")
#define _SHM_BASEMETHOD_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","basemethod_data.memory_ext_data_size")
#define _SHM_BASEMETHOD_EXTENTS_MAX_NUM_       SHMParamCfg::getValue("memory","basemethod_data.memory_max_extents")
#define _SHM_BASEMETHOD_DATA_KEYNAME_(x)       SHMParamCfg::getString("memory","basemethod_data.ipc_key_name",x)
#define _SHM_BASEMETHOD_INDEX_KEYNAME_(x)       SHMParamCfg::getString("memory","basemethod_index.ipc_key_name",x)
#define _SHM_BASEMETHOD_KEY_MAXSIZE_        8
#define _PV_BASEMETHOD_KEY_               SHMParamCfg::getValue("memory","basemethod_pv.ipc_key_value")

#define _SHM_PACKETSESSION_DATA_KEY_         SHMParamCfg::getValue("memory","packetsession_data.ipc_key_value")
#define _SHM_PACKETSESSION_INDEX_KEY_        SHMParamCfg::getValue("memory","packetsession_index.ipc_key_value")
#define _SHM_PACKETSUBSESSION_INDEX_KEY_        SHMParamCfg::getValue("memory","packetsubsession_index.ipc_key_value")
#define _SHM_PACKETSESSION_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","packetsession_data.init_data_size")
#define _SHM_PACKETSESSION_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","packetsession_data.max_data_size")
#define _SHM_PACKETSESSION_EXTENTS_NUM_       SHMParamCfg::getValue("memory","packetsession_data.memory_extents_num")
#define _SHM_PACKETSESSION_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","packetsession_data.memory_max_extents")
#define _SHM_PACKETSESSION_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","packetsession_data.memory_ext_data_size")
#define _SHM_PACKETSESSION_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","packetsession_data.memory_ext_hwm")
#define _SHM_PACKETSESSION_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","packetsession_data.shm_hwm_warming")
#define _SHM_PACKETSESSION_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","packetsession_data.ipc_key_name",x)
#define _SHM_PACKETSESSION_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","packetsession_index.ipc_key_name",x)
#define _SHM_PACKETSESSION_INDEX_KEYNAME_A_(x)           SHMParamCfg::getString("memory","packetsubsession_index.ipc_key_name",x)
#define _SHM_PACKETSESSION_KEY_MAXSIZE_        8
#define _PV_PACKETSESSION_KEY_               SHMParamCfg::getValue("memory","packetsession_pv.ipc_key_value")

#define _SHM_SERVICEPACKAGE_DATA_KEY_         SHMParamCfg::getValue("memory","servicepackage_data.ipc_key_value")
#define _SHM_SERVICEPACKAGE_INDEX_KEY_        SHMParamCfg::getValue("memory","servicepackage_index.ipc_key_value")
#define _SHM_SERVICEPACKAGE_INDEX_KEY_A_        SHMParamCfg::getValue("memory","servicepackage_a_index.ipc_key_value")
#define _SHM_SERVICEPACKAGE_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","servicepackage_data.init_data_size")
#define _SHM_SERVICEPACKAGE_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","servicepackage_data.max_data_size")
#define _SHM_SERVICEPACKAGE_EXTENTS_NUM_       SHMParamCfg::getValue("memory","servicepackage_data.memory_extents_num")
#define _SHM_SERVICEPACKAGE_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","servicepackage_data.memory_max_extents")
#define _SHM_SERVICEPACKAGE_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","servicepackage_data.memory_ext_data_size")
#define _SHM_SERVICEPACKAGE_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","servicepackage_data.memory_ext_hwm")
#define _SHM_SERVICEPACKAGE_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","servicepackage_data.shm_hwm_warming")
#define _SHM_SERVICEPACKAGE_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","servicepackage_data.ipc_key_name",x)
#define _SHM_SERVICEPACKAGE_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","servicepackage_index.ipc_key_name",x)
#define _SHM_SERVICEPACKAGE_INDEX_KEYNAME_A_(x)           SHMParamCfg::getString("memory","servicepackage_a_index.ipc_key_name",x)
#define _SHM_SERVICEPACKAGE_KEY_MAXSIZE_        8
#define _PV_SERVICEPACKAGE_KEY_               SHMParamCfg::getValue("memory","servicepackage_pv.ipc_key_value")

#define _SHM_PACKAGEROUTE_DATA_KEY_         SHMParamCfg::getValue("memory","packageroute_data.ipc_key_value")
#define _SHM_PACKAGEROUTE_INDEX_KEY_        SHMParamCfg::getValue("memory","packageroute_index.ipc_key_value")
#define _SHM_PACKAGEROUTE_INDEX_KEY_A_        SHMParamCfg::getValue("memory","packageroute_a_index.ipc_key_value")
#define _SHM_PACKAGEROUTE_SPACE_INITSIZE_        SHMParamCfg::getValue("memory","packageroute_data.init_data_size")
#define _SHM_PACKAGEROUTE_SPACE_MAXSIZE_        SHMParamCfg::getValue("memory","packageroute_data.max_data_size")
#define _SHM_PACKAGEROUTE_EXTENTS_NUM_       SHMParamCfg::getValue("memory","packageroute_data.memory_extents_num")
#define _SHM_PACKAGEROUTE_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","packageroute_data.memory_max_extents")
#define _SHM_PACKAGEROUTE_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","packageroute_data.memory_ext_data_size")
#define _SHM_PACKAGEROUTE_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","packageroute_data.memory_ext_hwm")
#define _SHM_PACKAGEROUTE_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","packageroute_data.shm_hwm_warming")
#define _SHM_PACKAGEROUTE_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","packageroute_data.ipc_key_name",x)
#define _SHM_PACKAGEROUTE_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","packageroute_index.ipc_key_name",x)
#define _SHM_PACKAGEROUTE_INDEX_KEYNAME_A_(x)           SHMParamCfg::getString("memory","packageroute_a_index.ipc_key_name",x)
#define _SHM_PACKAGEROUTE_KEY_MAXSIZE_        8
#define _PV_PACKAGEROUTE_KEY_               SHMParamCfg::getValue("memory","packageroute_pv.ipc_key_value")

#define _SHM_PACKAGEROUTECCR_DATA_KEY_         SHMParamCfg::getValue("memory","packagerouteccr_data.ipc_key_value")
#define _SHM_PACKAGEROUTECCR_INDEX_KEY_        SHMParamCfg::getValue("memory","packagerouteccr_index.ipc_key_value")
#define _SHM_PACKAGEROUTECCR_INDEX_KEY_A_       SHMParamCfg::getValue("memory","packagerouteccr_index_a.ipc_key_value")
#define _SHM_PACKAGEROUTECCR_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","packagerouteccr_data.init_data_size")
#define _SHM_PACKAGEROUTECCR_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","packagerouteccr_data.max_data_size")
#define _SHM_PACKAGEROUTECCR_EXTENTS_NUM_       SHMParamCfg::getValue("memory","packagerouteccr_data.memory_extents_num")
#define _SHM_PACKAGEROUTECCR_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","packagerouteccr_data.memory_max_extents")
#define _SHM_PACKAGEROUTECCR_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","packagerouteccr_data.memory_ext_data_size")
#define _SHM_PACKAGEROUTECCR_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","packagerouteccr_data.memory_ext_hwm")
#define _SHM_PACKAGEROUTECCR_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","packagerouteccr_data.shm_hwm_warming")
#define _SHM_PACKAGEROUTECCR_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","packagerouteccr_data.ipc_key_name",x)
#define _SHM_PACKAGEROUTECCR_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","packagerouteccr_index.ipc_key_name",x)
#define _SHM_PACKAGEROUTECCR_INDEX_KEYNAME_A_(x)           SHMParamCfg::getString("memory","packagerouteccr_index_a.ipc_key_name",x)
#define _SHM_PACKAGEROUTECCR_KEY_MAXSIZE_       8
#define _PV_PACKAGEROUTECCR_KEY_               SHMParamCfg::getValue("memory","packagerouteccr_pv.ipc_key_value")

#define _SHM_SERVICEPACKAGEJUDGE_DATA_KEY_         SHMParamCfg::getValue("memory","packagejudge_data.ipc_key_value")
#define _SHM_SERVICEPACKAGEJUDGE_INDEX_KEY_        SHMParamCfg::getValue("memory","packagejudge_index.ipc_key_value")
#define _SHM_SERVICEPACKAGEJUDGE_INDEX_KEY_A_       SHMParamCfg::getValue("memory","packagejudge_index_a.ipc_key_value")
#define  _SHM_SERVICEPACKAGEJUDGE_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","packagejudge_data.init_data_size")
#define  _SHM_SERVICEPACKAGEJUDGE_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","packagejudge_data.max_data_size")
#define _SHM_SERVICEPACKAGEJUDGE_EXTENTS_NUM_       SHMParamCfg::getValue("memory","packagejudge_data.memory_extents_num")
#define _SHM_SERVICEPACKAGEJUDGE_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","packagejudge_data.memory_max_extents")
#define _SHM_SERVICEPACKAGEJUDGE_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","packagejudge_data.memory_ext_data_size")
#define _SHM_SERVICEPACKAGEJUDGE_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","packagejudge_data.memory_ext_hwm")
#define _SHM_SERVICEPACKAGEJUDGE_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","packagejudge_data.shm_hwm_warming")
#define _SHM_SERVICEPACKAGEJUDGE_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","packagejudge_data.ipc_key_name",x)
#define _SHM_SERVICEPACKAGEJUDGE_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","packagejudge_index.ipc_key_name",x)
#define _SHM_SERVICEPACKAGEJUDGE_INDEX_KEYNAME_A_(x)           SHMParamCfg::getString("memory","packagejudge_index_a.ipc_key_name",x)
#define _SHM_SERVICEPACKAGEJUDGE_KEY_MAXSIZE_       8
#define _PV_SERVICEPACKAGEJUDGE_KEY_               SHMParamCfg::getValue("memory","packagejudge_pv.ipc_key_value")

#define _SHM_SERVICEPACKAGECCA_DATA_KEY_         SHMParamCfg::getValue("memory","service_package_cca_data.ipc_key_value")
#define _SHM_SERVICEPACKAGECCA_INDEX_KEY_        SHMParamCfg::getValue("memory","service_package_cca_index.ipc_key_value")
#define _SHM_SERVICEPACKAGECCA_INDEX_KEY_A_       SHMParamCfg::getValue("memory","service_package_cca_index_a.ipc_key_value")
#define  _SHM_SERVICEPACKAGECCA_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","service_package_cca_data.init_data_size")
#define  _SHM_SERVICEPACKAGECCA_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","service_package_cca_data.max_data_size")
#define _SHM_SERVICEPACKAGECCA_EXTENTS_NUM_       SHMParamCfg::getValue("memory","service_package_cca_data.memory_extents_num")
#define _SHM_SERVICEPACKAGECCA_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","service_package_cca_data.memory_max_extents")
#define _SHM_SERVICEPACKAGECCA_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","service_package_cca_data.memory_ext_data_size")
#define _SHM_SERVICEPACKAGECCA_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","service_package_cca_data.memory_ext_hwm")
#define _SHM_SERVICEPACKAGECCA_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","service_package_cca_data.shm_hwm_warming")
#define _SHM_SERVICEPACKAGECCA_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","service_package_cca_data.ipc_key_name",x)
#define _SHM_SERVICEPACKAGECCA_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","service_package_cca_index.ipc_key_name",x)
#define _SHM_SERVICEPACKAGECCA_INDEX_KEYNAME_A_(x)           SHMParamCfg::getString("memory","service_package_cca_index_a.ipc_key_name",x)
#define _SHM_SERVICEPACKAGECCA_KEY_MAXSIZE_       8
#define _PV_SERVICEPACKAGECCA_KEY_               SHMParamCfg::getValue("memory","service_package_cca_pv.ipc_key_value")

#define _SHM_SERVICEPACKAGEFUNC_DATA_KEY_         SHMParamCfg::getValue("memory","service_package_func_data.ipc_key_value")
#define _SHM_SERVICEPACKAGEFUNC_INDEX_KEY_        SHMParamCfg::getValue("memory","service_package_func_index.ipc_key_value")
#define _SHM_SERVICEPACKAGEFUNC_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","service_package_func_data.init_data_size")
#define _SHM_SERVICEPACKAGEFUNC_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","service_package_func_data.max_data_size")
#define _SHM_SERVICEPACKAGEFUNC_EXTENTS_NUM_       SHMParamCfg::getValue("memory","service_package_func_data.memory_extents_num")
#define _SHM_SERVICEPACKAGEFUNC_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","service_package_func_data.memory_max_extents")
#define _SHM_SERVICEPACKAGEFUNC_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","service_package_func_data.memory_ext_data_size")
#define _SHM_SERVICEPACKAGEFUNC_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","service_package_func_data.memory_ext_hwm")
#define _SHM_SERVICEPACKAGEFUNC_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","service_package_func_data.shm_hwm_warming")
#define _SHM_SERVICEPACKAGEFUNC_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","service_package_func_data.ipc_key_name",x)
#define _SHM_SERVICEPACKAGEFUNC_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","service_package_func_index.ipc_key_name",x)
#define _PV_SERVICEPACKAGEFUNC_KEY_               SHMParamCfg::getValue("memory","service_package_func_pv.ipc_key_value")

#define _SHM_SERVICEPACKAGEVLE_DATA_KEY_         SHMParamCfg::getValue("memory","service_package_vle_data.ipc_key_value")
#define _SHM_SERVICEPACKAGEVLE_INDEX_KEY_        SHMParamCfg::getValue("memory","service_package_vle_index.ipc_key_value")
#define _SHM_SERVICEPACKAGEVLE_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","service_package_vle_data.init_data_size")
#define _SHM_SERVICEPACKAGEVLE_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","service_package_vle_data.max_data_size")
#define _SHM_SERVICEPACKAGEVLE_EXTENTS_NUM_       SHMParamCfg::getValue("memory","service_package_vle_data.memory_extents_num")
#define _SHM_SERVICEPACKAGEVLE_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","service_package_vle_data.memory_max_extents")
#define _SHM_SERVICEPACKAGEVLE_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","service_package_vle_data.memory_ext_data_size")
#define _SHM_SERVICEPACKAGEVLE_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","service_package_vle_data.memory_ext_hwm")
#define _SHM_SERVICEPACKAGEVLE_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","service_package_vle_data.shm_hwm_warming")
#define _SHM_SERVICEPACKAGEVLE_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","service_package_vle_data.ipc_key_name",x)
#define _SHM_SERVICEPACKAGEVLE_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","service_package_vle_index.ipc_key_name",x)
#define _PV_SERVICEPACKAGEVLE_KEY_               SHMParamCfg::getValue("memory","service_package_vle_pv.ipc_key_value")

#define _SHM_SCONGESTMSG_DATA_KEY_         SHMParamCfg::getValue("memory","scongestmsg_data.ipc_key_value")
#define _SHM_SCONGESTMSG_INDEX_KEY_        SHMParamCfg::getValue("memory","scongestmsg_index.ipc_key_value")
#define _SHM_SCONGESTMSG_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","scongestmsg_data.init_data_size")
#define _SHM_SCONGESTMSG_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","scongestmsg_data.max_data_size")
#define _SHM_SCONGESTMSG_EXTENTS_NUM_       SHMParamCfg::getValue("memory","scongestmsg_data.memory_extents_num")
#define _SHM_SCONGESTMSG_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","scongestmsg_data.memory_max_extents")
#define _SHM_SCONGESTMSG_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","scongestmsg_data.memory_ext_data_size")
#define _SHM_SCONGESTMSG_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","scongestmsg_data.memory_ext_hwm")
#define _SHM_SCONGESTMSG_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","scongestmsg_data.shm_hwm_warming")
#define _SHM_SCONGESTMSG_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","scongestmsg_data.ipc_key_name",x)
#define _SHM_SCONGESTMSG_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","scongestmsg_index.ipc_key_name",x)
#define _SHM_SCONGESTMSG_KEY_MAXSIZE_       8
#define _PV_SCONGESTMSG_KEY_               SHMParamCfg::getValue("memory","scongestmsg_pv.ipc_key_value")

#define _SHM_WFPROCESSMQ_DATA_KEY_         SHMParamCfg::getValue("memory","wfprocessmq_data.ipc_key_value")
#define _SHM_WFPROCESSMQ_INDEX_KEY_        SHMParamCfg::getValue("memory","wfprocessmq_index.ipc_key_value")
#define _SHM_WFPROCESSMQ_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","wfprocessmq_data.init_data_size")
#define _SHM_WFPROCESSMQ_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","wfprocessmq_data.max_data_size")
#define _SHM_WFPROCESSMQ_EXTENTS_NUM_       SHMParamCfg::getValue("memory","wfprocessmq_data.memory_extents_num")
#define _SHM_WFPROCESSMQ_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","wfprocessmq_data.memory_max_extents")
#define _SHM_WFPROCESSMQ_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","wfprocessmq_data.memory_ext_data_size")
#define _SHM_WFPROCESSMQ_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","wfprocessmq_data.memory_ext_hwm")
#define _SHM_WFPROCESSMQ_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","wfprocessmq_data.shm_hwm_warming")
#define _SHM_WFPROCESSMQ_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","wfprocessmq_data.ipc_key_name",x)
#define _SHM_WFPROCESSMQ_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","wfprocessmq_index.ipc_key_name",x)
#define _PV_WFPROCESSMQ_KEY_               SHMParamCfg::getValue("memory","wfprocessmq_pv.ipc_key_value")

#define _SHM_PORTINFO_DATA_KEY_         SHMParamCfg::getValue("memory","portinfo_data.ipc_key_value")
#define _SHM_PORTINFO_INDEX_KEY_        SHMParamCfg::getValue("memory","portinfo_index.ipc_key_value")
#define _SHM_PORTINFO_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","portinfo_data.init_data_size")
#define _SHM_PORTINFO_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","portinfo_data.max_data_size")
#define _SHM_PORTINFO_EXTENTS_NUM_       SHMParamCfg::getValue("memory","portinfo_data.memory_extents_num")
#define _SHM_PORTINFO_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","portinfo_data.memory_max_extents")
#define _SHM_PORTINFO_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","portinfo_data.memory_ext_data_size")
#define _SHM_PORTINFO_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","portinfo_data.memory_ext_hwm")
#define _SHM_PORTINFO_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","portinfo_data.shm_hwm_warming")
#define _SHM_PORTINFO_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","portinfo_data.ipc_key_name",x)
#define _SHM_PORTINFO_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","portinfo_index.ipc_key_name",x)
#define _PV_PORTINFO_KEY_               SHMParamCfg::getValue("memory","portinfo_pv.ipc_key_value")

#define _SHM_ORGROUTE_DATA_KEY_         SHMParamCfg::getValue("memory","orgroute_data.ipc_key_value")
#define _SHM_ORGROUTE_INDEX_KEY_        SHMParamCfg::getValue("memory","orgroute_index.ipc_key_value")
#define _SHM_ORGROUTE_INDEX_KEY_A_        SHMParamCfg::getValue("memory","orgroute_index_a.ipc_key_value")
#define _SHM_ORGROUTE_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","orgroute_data.init_data_size")
#define _SHM_ORGROUTE_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","orgroute_data.max_data_size")
#define _SHM_ORGROUTE_EXTENTS_NUM_       SHMParamCfg::getValue("memory","orgroute_data.memory_extents_num")
#define _SHM_ORGROUTE_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","orgroute_data.memory_max_extents")
#define _SHM_ORGROUTE_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","orgroute_data.memory_ext_data_size")
#define _SHM_ORGROUTE_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","orgroute_data.memory_ext_hwm")
#define _SHM_ORGROUTE_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","orgroute_data.shm_hwm_warming")
#define _SHM_ORGROUTE_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","orgroute_data.ipc_key_name",x)
#define _SHM_ORGROUTE_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","orgroute_index.ipc_key_name",x)
#define _PV_ORGROUTE_KEY_               SHMParamCfg::getValue("memory","orgroute_pv.ipc_key_value")

#define _SHM_GLOBALMAP_DATA_KEY_         SHMParamCfg::getValue("memory","globalmap_data.ipc_key_value")
#define _SHM_GLOBALMAP_INDEX_KEY_        SHMParamCfg::getValue("memory","globalmap_index.ipc_key_value")
#define _SHM_GLOBALMAP_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","globalmap_data.init_data_size")
#define _SHM_GLOBALMAP_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","globalmap_data.max_data_size")
#define _SHM_GLOBALMAP_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","globalmap_data.ipc_key_name",x)
#define _SHM_GLOBALMAP_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","globalmap_index.ipc_key_name",x)
#define _PV_GLOBALMAP_KEY_               SHMParamCfg::getValue("memory","globalmap_pv.ipc_key_value")

#define _SHM_ORGHEAD_DATA_KEY_         SHMParamCfg::getValue("memory","orghead_data.ipc_key_value")
#define _SHM_ORGHEAD_INDEX_KEY_        SHMParamCfg::getValue("memory","orghead_index.ipc_key_value")
#define _SHM_ORGHEAD_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","orghead_data.init_data_size")
#define _SHM_ORGHEAD_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","orghead_data.max_data_size")
#define _SHM_ORGHEAD_EXTENTS_NUM_       SHMParamCfg::getValue("memory","orghead_data.memory_extents_num")
#define _SHM_ORGHEAD_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","orghead_data.memory_max_extents")
#define _SHM_ORGHEAD_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","orghead_data.memory_ext_data_size")
#define _SHM_ORGHEAD_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","orghead_data.memory_ext_hwm")
#define _SHM_ORGHEAD_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","orghead_data.shm_hwm_warming")
#define _SHM_ORGHEAD_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","orghead_data.ipc_key_name",x)
#define _SHM_ORGHEAD_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","orghead_index.ipc_key_name",x)
#define _PV_ORGHEAD_KEY_               SHMParamCfg::getValue("memory","orghead_pv.ipc_key_value")

#define _SHM_CHANNEL_DATA_KEY_         SHMParamCfg::getValue("memory","channel_data.ipc_key_value")
#define _SHM_CHANNEL_INDEX_KEY_        SHMParamCfg::getValue("memory","channel_index.ipc_key_value")
#define _SHM_CHANNEL_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","channel_data.init_data_size")
#define _SHM_CHANNEL_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","channel_data.max_data_size")
#define _SHM_CHANNEL_EXTENTS_NUM_       SHMParamCfg::getValue("memory","channel_data.memory_extents_num")
#define _SHM_CHANNEL_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","channel_data.memory_max_extents")
#define _SHM_CHANNEL_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","channel_data.memory_ext_data_size")
#define _SHM_CHANNEL_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","channel_data.memory_ext_hwm")
#define _SHM_CHANNEL_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","channel_data.shm_hwm_warming")
#define _SHM_CHANNEL_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","channel_data.ipc_key_name",x)
#define _SHM_CHANNEL_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","channel_index.ipc_key_name",x)
#define _PV_CHANNEL_KEY_               SHMParamCfg::getValue("memory","channel_pv.ipc_key_value")

//#define _SHM_STAFF_DATA_KEY_         SHMParamCfg::getValue("memory","staff_data.ipc_key_value")
//#define _SHM_STAFF_INDEX_KEY_        SHMParamCfg::getValue("memory","staff_index.ipc_key_value")
//#define _SHM_STAFF_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","staff_data.init_data_size")
//#define _SHM_STAFF_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","staff_data.max_data_size")
//#define _SHM_STAFF_EXTENTS_NUM_       SHMParamCfg::getValue("memory","staff_data.memory_extents_num")
//#define _SHM_STAFF_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","staff_data.memory_max_extents")
//#define _SHM_STAFF_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","staff_data.memory_ext_data_size")
//#define _SHM_STAFF_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","staff_data.memory_ext_hwm")
//#define _SHM_STAFF_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","staff_data.shm_hwm_warming")
//#define _SHM_STAFF_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","staff_data.ipc_key_name",x)
//#define _SHM_STAFF_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","staff_index.ipc_key_name",x)
//#define _PV_STAFF_KEY_               SHMParamCfg::getValue("memory","staff_pv.ipc_key_value")
//
//#define _SHM_NETCHANNEL_DATA_KEY_         SHMParamCfg::getValue("memory","newchannel_data.ipc_key_value")
//#define _SHM_NETCHANNEL_INDEX_KEY_        SHMParamCfg::getValue("memory","newchannel_index.ipc_key_value")
//#define _SHM_NETCHANNEL_INDEX_KEY_A_        SHMParamCfg::getValue("memory","newchannel_index_a.ipc_key_value")
//#define _SHM_NETCHANNEL_INDEX_KEY_B_        SHMParamCfg::getValue("memory","newchannel_index_b.ipc_key_value")
//#define _SHM_NETCHANNEL_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","newchannel_data.init_data_size")
//#define _SHM_NETCHANNEL_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","newchannel_data.max_data_size")
//#define _SHM_NETCHANNEL_EXTENTS_NUM_       SHMParamCfg::getValue("memory","newchannel_data.memory_extents_num")
//#define _SHM_NETCHANNEL_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","newchannel_data.memory_max_extents")
//#define _SHM_NETCHANNEL_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","newchannel_data.memory_ext_data_size")
//#define _SHM_NETCHANNEL_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","newchannel_data.memory_ext_hwm")
//#define _SHM_NETCHANNEL_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","newchannel_data.shm_hwm_warming")
//#define _SHM_NETCHANNEL_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","newchannel_data.ipc_key_name",x)
//#define _SHM_NETCHANNEL_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","newchannel_data.ipc_key_name",x)
//#define _PV_NETCHANNEL_KEY_               SHMParamCfg::getValue("memory","newchannel_pv.ipc_key_value")

#define _SHM_USERSTAFF_DATA_KEY_         SHMParamCfg::getValue("memory","userstaff_data.ipc_key_value")
#define _SHM_USERSTAFF_INDEX_KEY_        SHMParamCfg::getValue("memory","userstaff_index.ipc_key_value")
#define _SHM_USERSTAFF_INDEX_KEY_A_        SHMParamCfg::getValue("memory","userstaff_index_a.ipc_key_value")
#define _SHM_USERSTAFF_INDEX_KEY_B_        SHMParamCfg::getValue("memory","userstaff_index_b.ipc_key_value")
#define _SHM_USERSTAFF_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","userstaff_data.init_data_size")
#define _SHM_USERSTAFF_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","userstaff_data.max_data_size")
#define _SHM_USERSTAFF_EXTENTS_NUM_       SHMParamCfg::getValue("memory","userstaff_data.memory_extents_num")
#define _SHM_USERSTAFF_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","userstaff_data.memory_max_extents")
#define _SHM_USERSTAFF_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","userstaff_data.memory_ext_data_size")
#define _SHM_USERSTAFF_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","userstaff_data.memory_ext_hwm")
#define _SHM_USERSTAFF_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","userstaff_data.shm_hwm_warming")
#define _SHM_USERSTAFF_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","userstaff_data.ipc_key_name",x)
#define _SHM_USERSTAFF_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","userstaff_data.ipc_key_name",x)
#define _PV_USERSTAFF_KEY_               SHMParamCfg::getValue("memory","userstaff_pv.ipc_key_value")

#define _SHM_ORGROUTERULE_DATA_KEY_         SHMParamCfg::getValue("memory","orgrouterule_data.ipc_key_value")
#define _SHM_ORGROUTERULE_INDEX_KEY_        SHMParamCfg::getValue("memory","orgrouterule_index.ipc_key_value")
#define _SHM_ORGROUTERULE_INDEX_KEY_A_        SHMParamCfg::getValue("memory","orgrouterule_index_a.ipc_key_value")
#define _SHM_ORGROUTERULE_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","orgrouterule_data.init_data_size")
#define _SHM_ORGROUTERULE_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","orgrouterule_data.max_data_size")
#define _SHM_ORGROUTERULE_EXTENTS_NUM_       SHMParamCfg::getValue("memory","orgrouterule_data.memory_extents_num")
#define _SHM_ORGROUTERULE_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","orgrouterule_data.memory_max_extents")
#define _SHM_ORGROUTERULE_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","orgrouterule_data.memory_ext_data_size")
#define _SHM_ORGROUTERULE_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","orgrouterule_data.memory_ext_hwm")
#define _SHM_ORGROUTERULE_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","orgrouterule_data.shm_hwm_warming")
#define _SHM_ORGROUTERULE_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","orgrouterule_data.ipc_key_name",x)
#define _SHM_ORGROUTERULE_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","orgrouterule_data.ipc_key_name",x)
#define _PV_ORGROUTERULE_KEY_               SHMParamCfg::getValue("memory","orgrouterule_pv.ipc_key_value")

#define _SHM_AREAORG_DATA_KEY_         SHMParamCfg::getValue("memory","areaorg_data.ipc_key_value")
#define _SHM_AREAORG_INDEX_KEY_        SHMParamCfg::getValue("memory","areaorg_index.ipc_key_value")
#define _SHM_AREAORG_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","areaorg_data.init_data_size")
#define _SHM_AREAORG_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","areaorg_data.max_data_size")
#define _SHM_AREAORG_EXTENTS_NUM_       SHMParamCfg::getValue("memory","areaorg_data.memory_extents_num")
#define _SHM_AREAORG_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","areaorg_data.memory_max_extents")
#define _SHM_AREAORG_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","areaorg_data.memory_ext_data_size")
#define _SHM_AREAORG_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","areaorg_data.memory_ext_hwm")
#define _SHM_AREAORG_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","areaorg_data.shm_hwm_warming")
#define _SHM_AREAORG_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","areaorg_data.ipc_key_name",x)
#define _SHM_AREAORG_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","areaorg_data.ipc_key_name",x)
#define _PV_AREAORG_KEY_               SHMParamCfg::getValue("memory","areaorg_pv.ipc_key_value")

#define _SHM_TUXRELAIN_DATA_KEY_         SHMParamCfg::getValue("memory","tuxrelain_data.ipc_key_value")
#define _SHM_TUXRELAIN_INDEX_KEY_        SHMParamCfg::getValue("memory","tuxrelain_index.ipc_key_value")
#define _SHM_TUXRELAIN_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","tuxrelain_data.init_data_size")
#define _SHM_TUXRELAIN_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","tuxrelain_data.max_data_size")
#define _SHM_TUXRELAIN_EXTENTS_NUM_       SHMParamCfg::getValue("memory","tuxrelain_data.memory_extents_num")
#define _SHM_TUXRELAIN_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","tuxrelain_data.memory_max_extents")
#define _SHM_TUXRELAIN_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","tuxrelain_data.memory_ext_data_size")
#define _SHM_TUXRELAIN_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","tuxrelain_data.memory_ext_hwm")
#define _SHM_TUXRELAIN_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","tuxrelain_data.shm_hwm_warming")
#define _SHM_TUXRELAIN_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","tuxrelain_data.ipc_key_name",x)
#define _SHM_TUXRELAIN_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","tuxrelain_data.ipc_key_name",x)
#define _PV_TUXRELAIN_KEY_               SHMParamCfg::getValue("memory","tuxrelain_pv.ipc_key_value")

#define _SHM_TUXRELAOUT_DATA_KEY_         SHMParamCfg::getValue("memory","tuxrelaout_data.ipc_key_value")
#define _SHM_TUXRELAOUT_INDEX_KEY_        SHMParamCfg::getValue("memory","tuxrelaout_index.ipc_key_value")
#define _SHM_TUXRELAOUT_INDEX_KEY_A_        SHMParamCfg::getValue("memory","tuxrelaout_a_index.ipc_key_value")
#define _SHM_TUXRELAOUT_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","tuxrelaout_data.init_data_size")
#define _SHM_TUXRELAOUT_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","tuxrelaout_data.max_data_size")
#define _SHM_TUXRELAOUT_EXTENTS_NUM_       SHMParamCfg::getValue("memory","tuxrelaout_data.memory_extents_num")
#define _SHM_TUXRELAOUT_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","tuxrelaout_data.memory_max_extents")
#define _SHM_TUXRELAOUT_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","tuxrelaout_data.memory_ext_data_size")
#define _SHM_TUXRELAOUT_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","tuxrelaout_data.memory_ext_hwm")
#define _SHM_TUXRELAOUT_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","tuxrelaout_data.shm_hwm_warming")
#define _SHM_TUXRELAOUT_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","tuxrelaout_data.ipc_key_name",x)
#define _SHM_TUXRELAOUT_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","tuxrelaout_data.ipc_key_name",x)
#define _PV_TUXRELAOUT_KEY_               SHMParamCfg::getValue("memory","tuxrelaout_pv.ipc_key_value")

#define _SHM_SVRLIST_DATA_KEY_         SHMParamCfg::getValue("memory","svrlist_data.ipc_key_value")
#define _SHM_SVRLIST_INDEX_KEY_        SHMParamCfg::getValue("memory","svrlist_index.ipc_key_value")
#define _SHM_SVRLIST_INDEX_KEY_A_        SHMParamCfg::getValue("memory","svrlist_a_index.ipc_key_value")
#define _SHM_SVRLIST_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","svrlist_data.init_data_size")
#define _SHM_SVRLIST_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","svrlist_data.max_data_size")
#define _SHM_SVRLIST_EXTENTS_NUM_       SHMParamCfg::getValue("memory","svrlist_data.memory_extents_num")
#define _SHM_SVRLIST_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","svrlist_data.memory_max_extents")
#define _SHM_SVRLIST_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","svrlist_data.memory_ext_data_size")
#define _SHM_SVRLIST_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","svrlist_data.memory_ext_hwm")
#define _SHM_SVRLIST_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","svrlist_data.shm_hwm_warming")
#define _SHM_SVRLIST_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","svrlist_data.ipc_key_name",x)
#define _SHM_SVRLIST_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","svrlist_data.ipc_key_name",x)
#define _PV_SVRLIST_KEY_               SHMParamCfg::getValue("memory","svrlist_pv.ipc_key_value")

#define _SHM_SVRSPARAMRELA_DATA_KEY_         SHMParamCfg::getValue("memory","svrsparamrela_data.ipc_key_value")
#define _SHM_SVRSPARAMRELA_INDEX_KEY_        SHMParamCfg::getValue("memory","svrsparamrela_index.ipc_key_value")
#define _SHM_SVRSPARAMRELA_INDEX_KEY_A_        SHMParamCfg::getValue("memory","svrsparamrela_a_index.ipc_key_value")
#define _SHM_SVRSPARAMRELA_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","svrsparamrela_data.init_data_size")
#define _SHM_SVRSPARAMRELA_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","svrsparamrela_data.max_data_size")
#define _SHM_SVRSPARAMRELA_EXTENTS_NUM_       SHMParamCfg::getValue("memory","svrsparamrela_data.memory_extents_num")
#define _SHM_SVRSPARAMRELA_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","svrsparamrela_data.memory_max_extents")
#define _SHM_SVRSPARAMRELA_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","svrsparamrela_data.memory_ext_data_size")
#define _SHM_SVRSPARAMRELA_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","svrsparamrela_data.memory_ext_hwm")
#define _SHM_SVRSPARAMRELA_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","svrsparamrela_data.shm_hwm_warming")
#define _SHM_SVRSPARAMRELA_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","svrsparamrela_data.ipc_key_name",x)
#define _SHM_SVRSPARAMRELA_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","svrsparamrela_data.ipc_key_name",x)
#define _PV_SVRSPARAMRELA_KEY_               SHMParamCfg::getValue("memory","svrsparamrela_pv.ipc_key_value")

#define _SHM_SVRSPARAMLIST_DATA_KEY_         SHMParamCfg::getValue("memory","svrsparamlist_data.ipc_key_value")
#define _SHM_SVRSPARAMLIST_INDEX_KEY_        SHMParamCfg::getValue("memory","svrsparamlist_index.ipc_key_value")
#define _SHM_SVRSPARAMLIST_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","svrsparamlist_data.init_data_size")
#define _SHM_SVRSPARAMLIST_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","svrsparamlist_data.max_data_size")
#define _SHM_SVRSPARAMLIST_EXTENTS_NUM_       SHMParamCfg::getValue("memory","svrsparamlist_data.memory_extents_num")
#define _SHM_SVRSPARAMLIST_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","svrsparamlist_data.memory_max_extents")
#define _SHM_SVRSPARAMLIST_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","svrsparamlist_data.memory_ext_data_size")
#define _SHM_SVRSPARAMLIST_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","svrsparamlist_data.memory_ext_hwm")
#define _SHM_SVRSPARAMLIST_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","svrsparamlist_data.shm_hwm_warming")
#define _SHM_SVRSPARAMLIST_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","svrsparamlist_data.ipc_key_name",x)
#define _SHM_SVRSPARAMLIST_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","svrsparamlist_data.ipc_key_name",x)
#define _PV_SVRSPARAMLIST_KEY_               SHMParamCfg::getValue("memory","svrsparamlist_pv.ipc_key_value")

#define _SHM_SVRSREGISTER_DATA_KEY_         SHMParamCfg::getValue("memory","svrsregister_data.ipc_key_value")
#define _SHM_SVRSREGISTER_INDEX_KEY_        SHMParamCfg::getValue("memory","svrsregister_index.ipc_key_value")
#define _SHM_SVRSREGISTER_INDEX_KEY_A_        SHMParamCfg::getValue("memory","svrsregister_a_index.ipc_key_value")
#define _SHM_SVRSREGISTER_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","svrsregister_data.init_data_size")
#define _SHM_SVRSREGISTER_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","svrsregister_data.max_data_size")
#define _SHM_SVRSREGISTER_EXTENTS_NUM_       SHMParamCfg::getValue("memory","svrsregister_data.memory_extents_num")
#define _SHM_SVRSREGISTER_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","svrsregister_data.memory_max_extents")
#define _SHM_SVRSREGISTER_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","svrsregister_data.memory_ext_data_size")
#define _SHM_SVRSREGISTER_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","svrsregister_data.memory_ext_hwm")
#define _SHM_SVRSREGISTER_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","svrsregister_data.shm_hwm_warming")
#define _SHM_SVRSREGISTER_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","svrsregister_data.ipc_key_name",x)
#define _SHM_SVRSREGISTER_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","svrsregister_data.ipc_key_name",x)
#define _PV_SVRSREGISTER_KEY_               SHMParamCfg::getValue("memory","svrsregister_pv.ipc_key_value")

#define _SHM_PARAMINSLIST_DATA_KEY_         SHMParamCfg::getValue("memory","paraminslist_data.ipc_key_value")
#define _SHM_PARAMINSLIST_INDEX_KEY_        SHMParamCfg::getValue("memory","paraminslist_index.ipc_key_value")
#define _SHM_PARAMINSLIST_INDEX_KEY_A_        SHMParamCfg::getValue("memory","paraminslist_index_a.ipc_key_value")
#define _SHM_PARAMINSLIST_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","paraminslist_data.init_data_size")
#define _SHM_PARAMINSLIST_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","paraminslist_data.max_data_size")
#define _SHM_PARAMINSLIST_EXTENTS_NUM_       SHMParamCfg::getValue("memory","paraminslist_data.memory_extents_num")
#define _SHM_PARAMINSLIST_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","paraminslist_data.memory_max_extents")
#define _SHM_PARAMINSLIST_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","paraminslist_data.memory_ext_data_size")
#define _SHM_PARAMINSLIST_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","paraminslist_data.memory_ext_hwm")
#define _SHM_PARAMINSLIST_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","paraminslist_data.shm_hwm_warming")
#define _SHM_PARAMINSLIST_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","paraminslist_data.ipc_key_name",x)
#define _SHM_PARAMINSLIST_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","paraminslist_data.ipc_key_name",x)
#define _PV_PARAMINSLIST_KEY_               SHMParamCfg::getValue("memory","paraminslist_pv.ipc_key_value")

#define _SHM_SGWENUMAREA_DATA_KEY_         SHMParamCfg::getValue("memory","enumarea_data.ipc_key_value")
#define _SHM_SGWENUMAREA_INDEX_KEY_        SHMParamCfg::getValue("memory","enumarea_index.ipc_key_value")
#define _SHM_SGWENUMAREA_INDEX_KEY_A_        SHMParamCfg::getValue("memory","enumarea_index_a.ipc_key_value")
#define _SHM_SGWENUMAREA_SPACE_INITSIZE_       SHMParamCfg::getValue("memory","enumarea_data.init_data_size")
#define _SHM_SGWENUMAREA_SPACE_MAXSIZE_       SHMParamCfg::getValue("memory","enumarea_data.max_data_size")
#define _SHM_SGWENUMAREA_EXTENTS_NUM_       SHMParamCfg::getValue("memory","enumarea_data.memory_extents_num")
#define _SHM_SGWENUMAREA_EXTENTS_MAX_NUM_     SHMParamCfg::getValue("memory","enumarea_data.memory_max_extents")
#define _SHM_SGWENUMAREA_EXTENTS_SIZE_       SHMParamCfg::getValue("memory","enumarea_data.memory_ext_data_size")
#define _SHM_SGWENUMAREA_EXTENTS_MAX_HWM_           SHMParamCfg::getValue("memory","enumarea_data.memory_ext_hwm")
#define _SHM_SGWENUMAREA_EXTENTS_MAX_WARM_           SHMParamCfg::getValue("memory","enumarea_data.shm_hwm_warming")
#define _SHM_SGWENUMAREA_DATA_KEYNAME_(x)           SHMParamCfg::getString("memory","enumarea_data.ipc_key_name",x)
#define _SHM_SGWENUMAREA_INDEX_KEYNAME_(x)           SHMParamCfg::getString("memory","enumarea_data.ipc_key_name",x)
#define _PV_SGWENUMAREA_KEY_               SHMParamCfg::getValue("memory","enumarea_pv.ipc_key_value")


//查询的共享内存信息
typedef struct _SHMQueryInfo
{
	char m_sKey[16]; //共享内存的key(十六进制)
	long m_lKey;     //共享内存的key(十进制）
	char m_sOwner[32]; //归属用户
	char m_sIPCType[32]; //共享内存的类型（数据区/索引区）
	char m_sDataFrom[128]; //数据来源
	unsigned int m_iUsed;      //已经使用的字节数
	unsigned int m_iAllSize;    //总得空间大小
	char m_sUseRate[32];   //共享内存利用率
	int m_iNattch;   //连接数
	int m_iTotal;
	char m_sDataNbr[32];
	char  m_sLoadTime[24]; //加载时间
}SHMInfo;

#endif
